import type { Metadata } from "next";
import { Geologica } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const geologica = Geologica({
  variable: "--font-geologica",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geologica.className} antialiased`}>
        <Toaster />
        {children}
      </body>
    </html>
  );
}
